import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Narbar";
import Hero from "../components/Hero";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="page_wrapper">
          <div>
            <Navbar />
          </div>
          <div>
            <Hero />
          </div>
        </div>
      </main>
    </div>
  );
}
